### ISSUE TITLE
Add auto-acking functionality

### ISSUE THREAD

**Issue by tnierman** [clcollins/srepd#43]
As a user, I'd like the ability to initiate an "auto-ack" mode where, as alerts are created in PagerDuty, `srepd` automatically sees that an incoming alert is assigned to me and acknowledges it for me, so that I can continue to focus on my current task and do not need to break concentration to acknowledge the alert.

This functionality should automatically turn off if, after a short period of time, no alerts have been assigned to the user, that way new problems are still brought to Primary's attention.

**Comment by tnierman** [comment]
Additional suggestions from @iamkirkbater:
- A maximum alert "threshold", after which PD alerts begin notifying the user again. This is to avoid situations where the user loses track of the alert count and ends up under water
- An exclusion list for alerts that should always page Primary, so that the most impactful stuff is always known to the user at the moment it becomes a problem

**Comment by iamkirkbater** [comment]
Maybe before we get started we could think of some "stories" as to how this might work?  I'm also thinking we might want to do something like "If you opened an issue and logged in - THEN auto-ack other alerts, otherwise let them page you"

In that scenario I'm thinking of a situation where it's not a busy day and I've stepped away but I left the auto-ack running, and then I come back and I've missed a few pages because they were all auto-ack'd.

**Comment by clcollins** [comment]
Initial work completed by #73 

I'm going to follow up with rules to not auto-ack P1 alerts.  I'm not sure how to realistically code for "if I stepped away" in a way that would work for all preferences.  Since auto-ack is a toggle, I think for now the best practice would be to either turn off auto-ack if you step away, or turn off auto-refresh (which pauses auto-acking, but will restart auto-acking if it was on, when refreshing starts.)

**Comment by clcollins** [comment]
Fixed by #73

**Comment by clcollins** [comment]
Closing, as this is merged.
